services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - app-network
  movie-service:
    build:
      context: ./movie-service
    ports:
      - "8082:8082"
    networks:
      - app-network
  rest-gateway:
    build:
      context: ./rest-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - movie-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge