# k8s/postgres-movies.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-movies
  namespace: movie-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-movies
  template:
    metadata:
      labels:
        app: postgres-movies
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_MOVIES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-movies-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-movies
  namespace: movie-streaming
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-movies
