apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: movie-streaming
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.8
          ports:
            - containerPort: 2181
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
